. Einführung SSI 
. Aktuelle Umsetzung in der Praxis am Beispiel von OIDC
.. OIDC-Flow
... Teilnehmer
... Basic
... Technisch
.. Probleme
... Datenhoheit
... Anzahl der Teilnehmer 
... Potentielle Probleme (Datenschutz, weiterverkauf der Daten -> nur die Daten freigeben welche angebracht sind; worüber kann User selbst entscheiden?)
.. Technische Umsetzung 
... ID-Token
... Access-Token
... Json-Web-Token
. Decentralized Identifier
.. Einführung in DIDs
.. Teilnehmer
... Einführung Wallet & Agents
.. DID-Documents
.. Gegenüberstellung DID und SSI Konzept
. DIDComm 
.. Was ist DIDComm (erklärung es ist protokoll auf welchem die Kommunikation basiert)
.. Datenaustausch
... Verbindungsaufbau 
... Nachrichten 
.... Nachrichtenformate
.... Verschlüsselungstechniken
. Zentrale Identitätshaltung
.. Von Google-verwalteter Identität zu selbstbestimmt 
.. Praktischer Use-Case (Beantragen eines Ausweises + bestätigen des Alters an Dritten)
... VC Credential anfordern
.... was muss vorher gegeben sein? (meine + ausstellende Behörde müssen eine zugeordnete DID besitzen)
.... Verbindungsaufbau (wie komme ich überhaupt in Verbindung mit der ausstellenden Behörde? QR-Code scannen, auf Website nachschauen, ...)
.... Wie sieht mein beantragter Credential aus?
... Mein Alter nachweisen 
... Vom Credential zum wirklichen Nachweis
.... Warum kann Credential nicht einfahc so übergeben werden sondern es benötigt noch einen Zwischenschritt? Credential = komplettes Dokument, dh. trotzdem alle Daten drauf wenn diese einfach so weitergegeben werden 
.... Selective Attribute Disclosure (ist der Weg von VC zu VP) VC in Form von Ausweis nehmen und bestimmte Attribute rausstreichen um nur Alter nachweisen zu können 
... Verifiable Presentation  
... Fallback zu SSI Konzept -> VC = zentrale Datenhaltung; VP = so wenig Informationen wie möglich, so viele wie nötig 
. DIDComm vs. OIDC (Tabellenform + (erklären???))
. Bestehende Anwendungen aufbauend auf OIDC
.. OIDC4VC/VP
.. VC & VP auf Basis von OIDC erstellen und mit DIDComm vergleichen


*Umfang der Arbeit*

Diese Arbeit dient dem Einstieg in die Thematik der Self-Sovereign Identity. Sie soll die Grundlage für das Verständnis selbstbestimmter Identitäten im digitalen Kontext bilden und weiterhin einen Ausblick über technologische Umsetzungsmöglichkeiten geben. 

Dabei werden die Leser an aktuelle Autorisierungs- und Authentifizierungsprotokolle und Web-Standards wie OIDC herangeführt, um ein Verständnis für die derzeitige Problematik und Situation im Web zu entwickeln. Im Anschluss wenden wir den Blick in eine mögliche Lösungsalternative, welche durch "Decentralized Identifier" (DID) und das Protokoll "DIDComm" versucht das Konzept von SSI technisch zu realisieren. 
 

== Einführung in SSI

Um Sie in die SSI-Thematik einzuführen, wollen wir Ihnen zu Beginn drei grundsätzliche Szenarien vorstellen, in denen der heutige Web-Standard zu Problem mit ihrer digitalen Identität führt.

*Szenario 1:*

Stellen Sie sich vor, Sie möchten sich auf einer neuen Social-Media-Plattform registrieren. Um sich für ein Konto auf dieser Plattform zu registrieren, müssen Sie sich vorher als neuer Nutzer mit ihrem Google- oder Facebook Konto legitimieren bzw. anmelden. Das bedeutet, dass sie als Nutzer der Plattform, den Zugang zu ihren persönlichen Daten, einschließlich ihres Namens, ihrer E-Mail und ihrer Freundesliste, über ihr Google- oder Facebook-Konto gewähren. Außerdem haben Sie möglicherweise keine Kontrolle mehr darüber, wie Ihre Daten von der Plattform weitergegeben oder verwendet werden. Dies könnte zu Bedenken hinsichtlich des Datenschutzes und zu einem Mangel an Vertrauen in die Plattform führen. Außerdem können Nutzer, die kein Google- oder Facebook-Konto haben, von der Nutzung der Plattform ausgeschlossen werden, was wiederrum eine Zugangsbarriere darstellt.

*Szenario 2:*

Im zweiten Szenario müssen Sie gleichzeitig auch der Plattform ihr Alter nachweisen, wobei nur entscheidend ist, ob sie mindestens über 18 Jahre alt sind. Wie können Sie der Plattform glaubhaft nachweisen, dass Sie dieses Kriterium tatsächlich erfüllen, ohne weitere persönliche Daten offen zu legen? Plattformen lösen dieses Problem, indem Sie auf das Szenario 1 zurückgreifen und von einem Identitätsanbieter wie zum Beispiel Facebook diese Informationen abgreifen. Dabei verlieren Sie die Kontrolle Ihrer Daten. Sie können sich zum Beispiel auch über ein Video-Identity Verfahren authentifizieren und dadurch ihr Alter nachweisen. Wenn Sie an solch einem Verfahren bereits teilgenommen haben, wissen Sie wahrscheinlich auch, dass dabei all ihre Ausweisdaten digital gespeichert werden. Enthalten sind dabei auch Informationen wie zum Beispiel Ihr Geburtsort. Diese Informationen sind für die Plattform an sich irrelevant, selbst das Geburtsdatum ist eigentlich nicht relevant, da am Ende lediglich geprüft werden muss, ob Sie über 18 Jahre alt sind oder nicht, dennoch legen Sie diese zusätzlichen Informationen im Authentifizierungsprozess ungewollt offen. 

Auf diese Thematik wollen wir im später Verlauf unserer Ausarbeitung nochmal genauer eingehen.

*Szenario 3:*

Haben Sie sich schon mal darüber geärgert, dass wenn sie einen Dienst nutzen wollen, sich vorher registrieren zu müssen? In der Regel ist Ihnen dieser Prozess zu zeitaufwendig und Sie greifen aus Bequemlichkeit auf das Szenario 1 zurück, indem Sie den Dienst eines Identitätsanbieters nutzen. Wissen Sie am Ende noch, wo Sie überall registriert sind? Wie viele Nutzerkonten Sie haben? Welche Webseiten, über welche ihrer Daten verfügen und ob diese Daten dort auch tatsächlich sicher gelagert sind?  

Wir registrieren uns häufiger im Web als uns bewusst ist. Dabei existiert von uns nicht eine digitale Identität, sondern unzählige digitale Identitäten. Sie sind auf jeder Social-Media-Plattform registriert. Auch bei ihrem Arbeitgeber haben Sie sehr wahrscheinlich ein eigenes digital gespeichertes Profil. Sie Nutzen Zahlungsdienste, Streamingdienste, Lieferdienste, ihre digitale Identität liegt überall. Die Frage ist, warum ist das so?

Als das Web 2.0 entwickelt wurde, war im Fokus der Entwicklung, dass der Nutzer nicht nur den Inhalt im Netz konsumiert, sondern er als Prosument selbst Inhalte zur Verfügung stellt. Kommt Ihnen das bekannt vor? Jeder Social-Media-Post, jeder Blogeintrag, jedes YouTube Video, all das sind Inhalte, die von Nutzer generiert worden sind. Jeweils einzelne digitale Identitäten die auf jeder dieser Plattform ihre eigene Identität besitzen.

// offen ...

Der Name Self-Sovereign Identity, im deutschen selbstbestimmte Identität, ist selbstsprechend. Dabei umfasst es alle Facetten digitaler Identität und deren Verwaltung, wobei der Nutzer in den Mittelpunkt rückt. Denkt man an die eigene Verwaltung seiner Identitäten, so fällt schnell auf dass man eine Reihe von Identitäten besitzt und somit bei vielen verschiedenen Anwendungen Konten erstellt hat. Dabei gibt man den selben Datensatz ständig neu ein oder nutzt bestehende Konten für die Registrierung. Auch die Pflege der Daten muss manuell, über viele Konten verteilt geschehen. Der Ansatz der Self-Sovereign-Identity verfolgt das Ziel diesem Problem vorzubeugen und digitale Identitäten einmalig in die Hand des Resource Owners zu legen. Relying Parties sollen keine persönlichen Informationen halten und "zur Verfügung" stellen sondern die Resource Owner sollen die Daten in ihrer Hand halten und verteilen. Somit fällt die Dritte Instanz, auch Identity Provider genannt, weg und es besteht ein Datenaustausch nur zwischen der Relying Party und dem Resource Owner. *Irgendwas zu zeigen/nicht zeigen von Attributen -> drauf eingehen dass vorallem wichig das user nicht immer alle Daten zeigen muss - kann sich aussuchen welche Teile seiner Identität offengelegt werden* + Daten müssen in der Lage sein überprüfbar zu sein, ohne Abhängigkeit von Dritten


== OIDC
Um das Problem des aktuell herrschenden Problems besser verstehen zu können muss der Blick auf die derzeitige Umsetzung im Netz gelegt werden. Dieses Fenster [hier Bild einfügen für Login-Seite per Google, etc.] ist heutzutage ein Standard welcher unter dem Namen OIDC bekannt ist. Dabei handelt es sich um ein Authentifizierungsprotokoll welches es dem Nutzer ermöglicht sich mit einem bestehendem Account bei einer Relying Party zu registrieren. [Bild von OIDC Flow]
Wie man in Abbildung 2 erkennt, gehören zur Authentifizierung per OIDC 3 Partien. Der Resource Owner stellt die Entität dar welche ihre Identität beweisen möchte.
Der Identity Provider ist ein Anbieter welche es dem Resource Owner ermöglicht sich eine digitale Identität anzulegen und verwaltet diese. Der IP kann ein beliebiges Unternehmen sein, wobei die gängigsten Google, Facebook oder Apple sind. 
Die Relying Party ist die Anwendung welche vom Resource Owner Daten erheben möchte. Dies kann im Kontext eines Registrierungs-/Anmeldungs- oder Bestellvorgangs vorkommen. 
OIDC-Flow: 
* Voraussetzungen
** Anmeldung per OIDC ist durch Relying Party möglich 
** Der Resource Owner verfügt bereits über eine digitale Identität beim Identity Provider
* Use Case Annahmen
** RO = Peter Schmitt
** RP = Lieferando 
** IP = Apple
* Ablauf
** Peter Schmitt möchte bei Lieferando bestellen, hat aber keine Zeit sich selbst zu registrieren und möchte seinen Apple-Account dafür nutzen
** Lieferando leitet ihn auf die Authentifizierungsseite von Apple weiter, auf dieser muss er sich anmelden und Apple dazu befähigen seine Identität an Lieferando auszustellen 
*** Die benötigten Daten werden dabei im "Scope" adressiert 
**** Wie sieht ein Scope aus? [email, ]
** als Antwort erhält Lieferando ein ID-Token und ein Access-Token 
*** ID-Token dient der Authentifizierung des RO
*** Access-Token dient der Berechtigung zur Abfrage weiterer Daten des RO durch die Relying Party
** Der Lieferando-Account wird anhand der abgefragten Daten erstellt und Herr Schmitt kann seine Bestellung abschließen 

***Überleitung zu Problemen*** 
Der Vorteil für den Nutzer bei OIDC ist deutlich spürbar, da eine zentrale Verwaltung aller Konten über eine einzelne Identität möglich ist. Der Resource Owner verliert durch in Anspruchnahme dieser Dienste seine Datenhoheit. Die Identity Provider sind nun in der Lage die Daten der Resource Owner zu verkaufen und besitzen diese. Auch das explizite verdecken und freilegen bestimmter Attribute einer Identität sind nicht möglich. Der Scope einer Abfrage wird durch die Relying Party festgelegt, der Resource Owner kann beim Authentifizierungsprozess nur Zustimmen oder Ablehnen. Es gibt keine Möglichkeit selbstbestimmt die Datenmenge anzupassen. 
