:imagesdir: img

= 1. Ein technischer Vergleich von DIDComm und Open ID Connect

== DIDComm
.Was ist DIDComm?
* Protokoll für die Kommunikation bei DID basierten Kommunikationsverbindungen
** diese Verbindungen sind der Kern von SSI
* um eine Verbindung herzustellen werden DIDs (Decentralized Identifiers) ausgetauscht
** beide Kommunikationspartner sind selbst zertifiziert und sind sich einig über die gegenseitige Authentizität
* *ein sicheres, interoperables und flexibles* Kommunikationstool für das gesamte Internet
.Beispiel
//image::

.Eigenschaften von DIDComm
* sicher
* privat
* interoperabel
* Art der Verbindung ist unwichtig
* erweiterbar

* kein bestimnmtes Betriebssystem, Progrtammiersprache, Anbieter, Netzwerk oder hardware
* Ziel ist es, die standardmäßige Kommunikation bei sicheren, privaten Interaktionen im und außerhalb des Internets zu werden
* es können alle Arten von Verbindungen genutzt werden _(HTTP(s), Websockets, IRC, Bluetooth, NFC, Signal, email, push benachrichtigungen, etc.)_

.DIDComm Protokolle
Kernfunktionen:
* Verbindung mit Partnern
* Credentials anfordern und ausstellen
* mithilfe von Credentials authentifizieren

== Open ID Connect
.Was ist OIDC?
* einfachte Identitäts Layer über dem OAuth 2.0 Protokoll
* Ermöglicht es dem Client, Endbenutzer zu identifizieren und einfache Informationen über ihn zu erhalten.
* alle Arten von Clients sind möglich

.Wie funktioniert OIDC?
image::IMG_0019jpg[]

== Vergleich





=== Quellen
* https://identity.foundation/didcomm-messaging/spec/
* https://www.windley.com/archives/2020/11/didcomm_and_the_self-sovereign_internet.shtml
