== Der Unterschied zwischen OIDC und OIDC4VP / OIDC4VC


Open ID Connect definiert Spezifikationen für das Ausgeben und Präsentieren von Berechtigungen.
Zusätzlich führt OIDC For Verifiable Credentials ein Wallet ein, welches es ermöglicht, Berechtigungen und die Nachweise dazu zu speichern. OIDC regelt die Interaktion zweier Parteien (Identity Provider & Relying Party) mithilfe eines User Agents, welcher aber nicht OIDC spezifisch ist.
Mithilfe von OID4VC ist die Abhängigkeit von IdP und RP nicht mehr gegeben, die Wallet beweißt automatisch die Berechtigung, identifiziert den Benutzer.

OpenID4VC
Nutzer kann seine Credentials selbst anlegen, verwalten und daraus "präsentierbare" Artefakte generieren. Jegliche Daten liegen im Wallet des Nutzers, wodurch eine zentralisierte Datenverwaltung gegeben ist.

OpenID4VP
VC's können angefordert und zur Präsentation freigegeben werden. Der Nutzer ist in der Lage, eigene "Pakete" von Informationen zu erstellen und diese zu VP's zusammenzufassen. Möchte eine Entität im späteren Verlauf diese Daten verifizieren, so kann der Holder diese zur Authentifizierung freigeben. 

Support of SSI
- Nutzerzentralisierung
- Daten sind zu jeder Zeit lokal verwaltbar
- Datenhoheit des Holders steht im Vordergrund
- Keine aktive Einbindung Dritter



== How does OpenID4VC / VP support the idea of SSI?

==== quellen
https://www.windley.com/archives/2022/10/using_openid4vc_for_credential_exchange.shtml
https://openid.net/wordpress-content/uploads/2022/06/OIDF-Whitepaper_OpenID-for-Verifiable-Credentials-V2_2022-06-23.pdf
https://openid.net/connect/
https://openid.net/connect/faq/